export const ICON_EMOJI: Record<string, string> = {
  compass: '🧭',
  shield: '🛡️',
  code: '⌨️',
  database: '🗄️',
  brain: '🧠',
  network: '🕸️',
  server: '🖥️',
  cloud: '☁️',
  wrench: '🔧',
  book: '📖',
  tool: '🛠️',
  puzzle: '🧩',
  rocket: '🚀',
  lightbulb: '💡',
  layers: '🗂️',
  link: '🔗',
  message: '💬',
  template: '📋',
  output: '📤',
  workflow: '🔀',
  pause: '⏸️',
  radio: '📻',
  history: '🕘',
  sync: '🔄',
  refresh: '🌀',
  map: '🗺️',
  cube: '🧊',
  settings: '⚙️',
  scissors: '✂️',
  sort: '↕️',
  edit: '✏️',
  gauge: '📊',
  bug: '🐛',
  activity: '📈',
  trending: '📉',
  trophy: '🏆',
};

export const DEPTH_LABELS: Record<string, string> = {
  Recognize: '认识',
  Understand: '理解',
  Use: '应用',
  Transfer: '迁移',
  DeepMastery: '深度掌握',
};
