import type { LearningTreeSnapshot } from '../types/learning';

const objectives = (items: string[]) => JSON.stringify(items);
const concepts = (items: string[]) => JSON.stringify(items);

/**
 * 内置演示技能树：没有配套后端时也能看到完整的节点图交互效果。
 * 启动配套后端后，前端会自动切换到真实学习进度数据。
 */
export const DEMO_TREE: LearningTreeSnapshot = {
  tree: {
    id: 'demo-nestjs-tree',
    topic: 'NestJS',
    title: 'NestJS 后端开发技能树',
    description: '演示数据：无需后端即可预览技能树交互效果',
    difficulty_level: '中级',
    total_nodes: 9,
  },
  current_node_id: 'controllers-routing',
  nodes: [
    {
      id: 'ts-basics',
      tree_id: 'demo-nestjs-tree',
      title: 'TypeScript 基础',
      description: '类型系统、接口、泛型与装饰器语法',
      icon: 'code',
      category: '语言基础',
      difficulty: 1,
      estimated_minutes: 120,
      depth_level: 1,
      position_x: 0,
      position_y: 0,
      order_in_level: 0,
      learning_objectives: objectives(['写出带类型标注的函数与接口', '理解泛型的约束与推断']),
      key_concepts: concepts(['interface', 'generic', 'decorator']),
      recommended_depth: 'Understand',
      depth_rationale: '作为工具语言，达到能读懂并能正确使用即可。',
      observable_evidence: '能独立完成带类型定义的小型工具函数。',
    },
    {
      id: 'node-runtime',
      tree_id: 'demo-nestjs-tree',
      title: 'Node.js 运行时',
      description: '事件循环、模块系统与 npm 生态',
      icon: 'server',
      category: '运行时',
      difficulty: 1,
      estimated_minutes: 90,
      depth_level: 1,
      position_x: 0,
      position_y: 0,
      order_in_level: 1,
      learning_objectives: objectives(['理解事件循环与异步模型', '掌握 CommonJS 与 ESM 模块机制']),
      key_concepts: concepts(['event loop', 'npm', 'module']),
      recommended_depth: 'Understand',
      depth_rationale: '运行时常识，理解即可，细节由框架封装。',
      observable_evidence: '能解释一个异步代码的执行顺序。',
    },
    {
      id: 'nest-modules',
      tree_id: 'demo-nestjs-tree',
      title: 'NestJS 模块系统',
      description: '@Module 装饰器、模块组织与依赖图',
      icon: 'compass',
      category: '框架核心',
      difficulty: 2,
      estimated_minutes: 150,
      depth_level: 2,
      position_x: 0,
      position_y: 0,
      order_in_level: 0,
      learning_objectives: objectives(['按业务域划分模块', '正确配置 imports 与 exports']),
      key_concepts: concepts(['@Module', 'feature module', 'module graph']),
      recommended_depth: 'Use',
      depth_rationale: '模块是 Nest 架构骨架，需要熟练应用。',
      observable_evidence: '能独立搭建一个多模块项目结构。',
    },
    {
      id: 'di-providers',
      tree_id: 'demo-nestjs-tree',
      title: '依赖注入与 Provider',
      description: 'Provider 注册、作用域与自定义 Token',
      icon: 'wrench',
      category: '框架核心',
      difficulty: 2,
      estimated_minutes: 180,
      depth_level: 2,
      position_x: 0,
      position_y: 0,
      order_in_level: 1,
      learning_objectives: objectives(['理解 IoC 容器的工作方式', '使用工厂与值 Provider 注入依赖']),
      key_concepts: concepts(['DI', 'provider', 'token', 'scope']),
      recommended_depth: 'Use',
      depth_rationale: 'DI 是 Nest 的引擎，是后续所有能力的地基。',
      observable_evidence: '能自定义一个带参数的服务并注入使用。',
    },
    {
      id: 'controllers-routing',
      tree_id: 'demo-nestjs-tree',
      title: '控制器与路由',
      description: '路由映射、请求参数装饰器与响应处理',
      icon: 'network',
      category: 'Web 层',
      difficulty: 2,
      estimated_minutes: 120,
      depth_level: 3,
      position_x: 0,
      position_y: 0,
      order_in_level: 0,
      learning_objectives: objectives(['用装饰器声明 REST 路由', '处理路径参数、查询参数与请求体']),
      key_concepts: concepts(['@Controller', '@Get', '@Param', '@Body']),
      recommended_depth: 'Use',
      depth_rationale: 'HTTP 入口，属于高频使用的基础能力。',
      observable_evidence: '能实现一组完整的 CRUD 接口。',
    },
    {
      id: 'services-layer',
      tree_id: 'demo-nestjs-tree',
      title: '服务层与业务逻辑',
      description: '业务编排、事务边界与领域服务设计',
      icon: 'brain',
      category: '架构设计',
      difficulty: 3,
      estimated_minutes: 200,
      depth_level: 3,
      position_x: 0,
      position_y: 0,
      order_in_level: 1,
      learning_objectives: objectives(['把业务规则收敛到服务层', '设计清晰的领域服务边界']),
      key_concepts: concepts(['service', 'business rule', 'transaction']),
      recommended_depth: 'Transfer',
      depth_rationale: '业务质量决定项目上限，需要能迁移到不同场景。',
      observable_evidence: '能把一个多步业务流程拆成可测试的服务方法。',
    },
    {
      id: 'guards-middleware',
      tree_id: 'demo-nestjs-tree',
      title: '守卫与中间件',
      description: '鉴权守卫、管道校验与拦截器',
      icon: 'shield',
      category: 'Web 层',
      difficulty: 2,
      estimated_minutes: 150,
      depth_level: 3,
      position_x: 0,
      position_y: 0,
      order_in_level: 2,
      learning_objectives: objectives(['实现路由级鉴权守卫', '用管道统一校验输入参数']),
      key_concepts: concepts(['Guard', 'Pipe', 'Interceptor']),
      recommended_depth: 'Use',
      depth_rationale: '安全与校验是接口质量的底线，必须熟练。',
      observable_evidence: '能为一组接口统一加鉴权与校验。',
    },
    {
      id: 'database-integration',
      tree_id: 'demo-nestjs-tree',
      title: '数据库集成',
      description: 'TypeORM 实体映射、数据源配置与迁移',
      icon: 'database',
      category: '数据层',
      difficulty: 3,
      estimated_minutes: 240,
      depth_level: 4,
      position_x: 0,
      position_y: 0,
      order_in_level: 0,
      learning_objectives: objectives(['定义实体与关系映射', '用迁移脚本管理表结构变更']),
      key_concepts: concepts(['TypeORM', 'entity', 'migration']),
      recommended_depth: 'Transfer',
      depth_rationale: '数据层方案随项目差异大，需要迁移能力。',
      observable_evidence: '能从零为项目接入数据库并完成一次迁移。',
    },
    {
      id: 'microservices',
      tree_id: 'demo-nestjs-tree',
      title: '微服务架构',
      description: '消息驱动通信、服务拆分与可观测性',
      icon: 'cloud',
      category: '架构设计',
      difficulty: 5,
      estimated_minutes: 360,
      depth_level: 5,
      position_x: 0,
      position_y: 0,
      order_in_level: 0,
      learning_objectives: objectives(['设计服务拆分边界', '用消息队列实现服务间通信']),
      key_concepts: concepts(['microservice', 'message broker', 'observability']),
      recommended_depth: 'DeepMastery',
      depth_rationale: '架构级能力，需要沉淀成可复用的设计判断。',
      observable_evidence: '能独立设计并落地一个多服务架构。',
    },
  ],
  edges: [
    { id: 'e1', source_node_id: 'ts-basics', target_node_id: 'nest-modules', edge_type: 'prerequisite', label: null },
    { id: 'e2', source_node_id: 'node-runtime', target_node_id: 'nest-modules', edge_type: 'prerequisite', label: null },
    { id: 'e3', source_node_id: 'nest-modules', target_node_id: 'di-providers', edge_type: 'prerequisite', label: null },
    { id: 'e4', source_node_id: 'di-providers', target_node_id: 'controllers-routing', edge_type: 'prerequisite', label: null },
    { id: 'e5', source_node_id: 'controllers-routing', target_node_id: 'services-layer', edge_type: 'prerequisite', label: null },
    { id: 'e6', source_node_id: 'controllers-routing', target_node_id: 'guards-middleware', edge_type: 'prerequisite', label: null },
    { id: 'e7', source_node_id: 'services-layer', target_node_id: 'database-integration', edge_type: 'prerequisite', label: null },
    { id: 'e8', source_node_id: 'guards-middleware', target_node_id: 'database-integration', edge_type: 'prerequisite', label: null },
    { id: 'e9', source_node_id: 'database-integration', target_node_id: 'microservices', edge_type: 'prerequisite', label: null },
  ],
  progress: [
    { node_id: 'ts-basics', status: 'mastered', evidence: '已完成类型工具函数练习' },
    { node_id: 'node-runtime', status: 'mastered', evidence: '已完成异步执行顺序实验' },
    { node_id: 'nest-modules', status: 'completed', evidence: '已搭建多模块项目结构' },
    { node_id: 'di-providers', status: 'completed', evidence: '已完成自定义 Provider 注入' },
    { node_id: 'controllers-routing', status: 'in_progress', evidence: '正在实现 CRUD 接口' },
    { node_id: 'services-layer', status: 'not_started', evidence: '' },
    { node_id: 'guards-middleware', status: 'not_started', evidence: '' },
    { node_id: 'database-integration', status: 'not_started', evidence: '' },
    { node_id: 'microservices', status: 'not_started', evidence: '' },
  ],
};
