import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { readModelPricing,formatAmountMicros } from './walletClient';
import WalletBalance from './WalletBalance';

const button = 'rounded-xl border border-slate-700 px-3 py-2 text-sm font-medium transition hover:border-cyan-500 hover:text-cyan-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300';

export default function ModelPricingPage({ accountId, onBack, onNavigateTavern, onNavigateWallet }: { accountId: string; onBack: () => void; onNavigateTavern: () => void; onNavigateWallet: () => void }) {
  const catalog = useQuery({ queryKey: ['model-catalog', 'pricing'], queryFn: readModelPricing, retry: false, staleTime: 60_000 });
  const [search, setSearch] = useState('');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const models = (catalog.data?.models ?? []).filter(model => `${model.id} ${model.provider}`.toLowerCase().includes(search.trim().toLowerCase()));
  const selected = models.find(model => model.id === selectedId) ?? models[0];

  return <div className="h-dvh min-h-0 overflow-y-auto overflow-x-hidden bg-slate-950 text-slate-100">
    <header className="sticky top-0 z-20 border-b border-slate-800 bg-slate-950/95 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center gap-3 px-4 py-3 sm:px-8"><button type="button" className={button} onClick={onBack}>返回</button><h1 className="min-w-0 truncate text-base font-semibold sm:text-lg">模型价格</h1><div className="ml-auto"><WalletBalance accountId={accountId} onClick={onNavigateWallet} /></div></div></header>
    <main className="mx-auto max-w-7xl px-4 py-6 sm:px-8 sm:py-8">
      <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Model Library</p><h2 className="text-2xl font-semibold tracking-tight sm:text-3xl">找到适合你的模型</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">{catalog.data?.models.some(model=>model.availability==='wallet')?'平台模型已支持现金额度：按上游实际扣费 × 2 结算。自填 Key 使用自己的上游余额。':'查看模型、渠道与参数。目前使用自填 Key，额度调用尚未开放。'}</p></div><button type="button" className={button} onClick={onNavigateTavern}>前往酒馆 <span aria-hidden="true">↗</span></button></div>
      {catalog.isPending && <p role="status" className="py-20 text-center text-sm text-slate-400">正在读取模型目录…</p>}
      {catalog.error && <div role="alert" className="rounded-2xl border border-rose-400/25 bg-rose-400/10 p-5 text-sm text-rose-300">{catalog.error.message} <button type="button" className={`${button} ml-2`} onClick={() => void catalog.refetch()}>重试</button></div>}
      {catalog.data && <div className="grid items-start gap-5 lg:grid-cols-[minmax(15rem,19rem)_minmax(0,1fr)]">
        <aside className="min-w-0 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/70 lg:sticky lg:top-24" aria-label="模型列表">
          <div className="border-b border-slate-800 p-4"><label className="relative block"><span className="sr-only">搜索模型</span><svg aria-hidden="true" className="absolute left-3 top-3.5 h-4 w-4 text-slate-500" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="8.5" cy="8.5" r="5.5" /><path d="m13 13 4 4" /></svg><input aria-label="搜索模型" value={search} onChange={event => setSearch(event.target.value)} placeholder="搜索模型或厂商" className="w-full min-w-0 rounded-xl border border-slate-700 bg-slate-950 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-cyan-400" /></label><p className="mt-3 text-xs text-slate-500">{models.length} 个模型</p></div>
          <ul className="max-h-64 space-y-1 overflow-y-auto p-2 lg:max-h-[calc(100dvh-17rem)]">{models.map(model => <li key={model.id}><button type="button" aria-label={`选择模型 ${model.id}`} aria-pressed={selected?.id === model.id} onClick={() => setSelectedId(model.id)} className={`flex w-full min-w-0 items-center gap-3 rounded-xl border px-3 py-3 text-left transition ${selected?.id === model.id ? 'border-cyan-300/25 bg-cyan-400/10' : 'border-transparent hover:bg-slate-800/70'}`}><span aria-hidden="true" className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border text-sm font-semibold ${selected?.id === model.id ? 'border-cyan-300/25 text-cyan-200' : 'border-slate-700 text-slate-400'}`}>{model.provider.slice(0, 1).toUpperCase()}</span><span className="min-w-0 flex-1"><span className={`block break-all text-sm font-medium ${selected?.id === model.id ? 'text-cyan-100' : 'text-slate-200'}`}>{model.id}</span><span className="mt-1 block text-xs text-slate-500">{model.provider}</span></span>{selected?.id === model.id && <span aria-hidden="true" className="text-cyan-300">›</span>}</button></li>)}</ul>
          {models.length === 0 && <p className="p-6 text-center text-sm text-slate-400">没有找到匹配的模型</p>}
        </aside>
        <section aria-label="模型详情" className="min-w-0 space-y-5">
          {selected ? <>
            <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 sm:p-6"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-slate-700 px-2.5 py-1 text-xs text-slate-400">{selected.provider}</span><span className="rounded-full bg-cyan-300/10 px-2.5 py-1 text-xs text-cyan-200">{selected.availability==='wallet'?'现金额度':'自填 Key'}</span></div><h2 className="mt-4 break-all text-2xl font-semibold leading-snug tracking-tight sm:text-3xl">{selected.id}</h2><div className="mt-6 grid grid-cols-2 gap-4 border-t border-slate-800 pt-5"><div><p className="text-xs text-slate-500">上下文窗口</p><p className="mt-2 break-all font-mono text-xl font-medium text-slate-200">{selected.contextWindow.toLocaleString()}</p><p className="mt-1 text-xs text-slate-500">Tokens</p></div><div><p className="text-xs text-slate-500">调用价格</p><p className="mt-2 text-lg font-medium text-slate-300">{selected.pricing?`输入 ¥${formatAmountMicros(selected.pricing.maxInputMicrosPerMillion)} · 输出 ¥${formatAmountMicros(selected.pricing.maxOutputMicrosPerMillion)} / 百万 Token（渠道最高价）`:(selected.availability==='wallet'?'价格暂时无法获取':'单价待配置')}</p><p className="mt-1 text-xs leading-5 text-slate-500">{selected.availability==='wallet'?'以下价格已含本站倍率；最终账单按上游实扣 × 2，缓存以实扣为准。':'自填 Key 按渠道实际价格计费'}</p></div></div></div>
            <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 sm:p-6"><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="font-semibold">渠道与可用性</h3><span className="text-xs text-slate-500">{selected.vendorCodes.length} 个公开渠道</span></div><p className="mt-2 text-xs leading-6 text-slate-500">{selected.pricing?`服务端获取的渠道快照，更新于 ${new Date(selected.pricing.updatedAt).toLocaleString()}；渠道由上游自动路由。`:'实际可用性取决于你的 Key 和所选渠道。'}</p><ul className="mt-5 space-y-5">{selected.pricing?selected.pricing.channels.map(channel=><li key={`${channel.vendor}.${channel.lane}`} className="rounded-xl border border-slate-800 p-4">
  <div className="flex flex-wrap justify-between gap-2"><span className="text-sm text-slate-300">{channel.vendor} · {channel.lane}</span><span className={channel.enabled?'text-xs text-emerald-300':'text-xs text-slate-500'}>{channel.enabled?'可用':'暂不可用'}</span></div>
  <p className="mt-2 text-xs text-cyan-200">输入 ¥{formatAmountMicros(channel.inputMicrosPerMillion)} · 输出 ¥{formatAmountMicros(channel.outputMicrosPerMillion)} / 百万 Token</p>
  <p className="mt-2 text-xs text-slate-400"><span>{channel.statsSource==='live'?'真实监控':channel.statsSource==='estimated'?'估算数据':'暂无监测数据'}</span>
    {channel.statsSource!=='unknown'&&channel.successRate24h!==null&&` · 24 小时成功率 ${channel.successRate24h}%`}
    {channel.statsSource!=='unknown'&&channel.avgResponseSeconds!==null&&` · 平均响应 ${channel.avgResponseSeconds} 秒`}</p>
</li>):selected.vendorCodes.map(code=><li key={code} className="flex justify-between gap-4 text-sm"><span>{code}</span><span className="text-xs text-slate-500">暂无监测数据</span></li>)}</ul>{selected.vendorCodes.length === 0 && <p className="mt-4 rounded-xl border border-dashed border-slate-700 py-8 text-center text-sm text-slate-500">暂无公开渠道</p>}</div>
            <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 sm:p-6"><h3 className="font-semibold">模型参数</h3><p className="mt-2 text-xs leading-6 text-slate-500">可在酒馆的模型设置中调整。</p>{selected.settings.length ? <dl className="mt-4 divide-y divide-slate-800">{selected.settings.map(setting => <div key={setting.name} className="flex flex-col justify-between gap-3 py-4 first:pt-1 sm:flex-row sm:items-center"><dt className="min-w-0 break-all font-mono text-sm text-slate-300">{setting.name}</dt><dd className="flex flex-wrap gap-1.5">{setting.kind === 'switch' ? <span className="rounded-lg border border-slate-700 px-2.5 py-1 text-xs text-slate-400">开 / 关</span> : setting.options.map(option => <span key={option} className="rounded-lg border border-slate-700 px-2.5 py-1 text-xs text-slate-400">{option}</span>)}</dd></div>)}</dl> : <p className="mt-5 text-sm text-slate-500">无额外参数</p>}</div>
          </> : <div className="rounded-2xl border border-dashed border-slate-700 p-12 text-center text-sm text-slate-500">换个关键词，试试其他模型。</div>}
        </section>
      </div>}
      <footer className="mt-7 border-t border-slate-800 pt-4 text-right text-xs text-slate-500">{catalog.data?.multiplierLabel??'上游实扣 × 2'}</footer>
    </main>
  </div>;
}
